version: '3.8'
services:
  app:
    restart: always
    container_name: online-judge
    build:
      context: ./
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
      - uploads:/app/uploads
    ports:
      - '8080:8080'

volumes:
  uploads:
