version: '2'

services:
  deepstream:
    restart: always
    image: deepstreamio/deepstream.io
    ports:
      - '6020:6020'
    volumes:
      - ./deepstream:/conf

  mongos:
    image: mongo
    container_name: mongos
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
    depends_on:
      - router1
    entrypoint: ['bash', '/scripts/mongo-router.sh']

  router1:
    image: mongo
    restart: always
    container_name: mongo-router1
    command: mongos --port 27017 --configdb config/configsvr01:27017 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb

  ## Config Servers
  configsvr:
    image: mongo
    restart: always
    container_name: mongo-config
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    depends_on:
      - configsvr01
    entrypoint: ['bash', '/scripts/mongo-server.sh']

  configsvr01:
    image: mongo
    restart: always
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet config
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    depends_on:
      - shard01-a
      - shard02-a

  ## Shard 1
  shard1:
    image: mongo
    restart: always
    container_name: shard1
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    depends_on:
      - shard01-a
    entrypoint: ['bash', '/scripts/mongo-shard1.sh']

  shard01-a:
    image: mongo
    restart: always
    container_name: shard1-1
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017

  ## Shard 2
  shard2:
    image: mongo
    restart: always
    container_name: shard2
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    depends_on:
      - shard02-a
    entrypoint: ['bash', '/scripts/mongo-shard2.sh']

  shard02-a:
    image: mongo
    restart: always
    container_name: shard2-1
    command: mongod --port 27017 --shardsvr --replSet shard2
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27017

volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:

  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:

  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:

  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:
